### ISSUE TITLE
compatibility issues

### ISSUE THREAD

**Issue by stefangweichinger** [robertdebock/docker-github-action-molecule#10]
Does your action read `collections.yml` ? I am trying to fix an issue in https://github.com/stefangweichinger/ansible-rclone/pull/104 and it seems that the action does not follow the requirements in https://github.com/stefangweichinger/ansible-rclone/blob/0f12fe870281e321ad2089b2f2e514d8e7d86d78/molecule/default/collections.yml

The original issue seems to be this one: https://github.com/ansible-community/molecule/issues/2755

**Comment by stefangweichinger** [comment]
Cloned your repo and added this to the Dockerfile:

```
diff --git a/Dockerfile b/Dockerfile
index 130f800..fe8b7c1 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -23,6 +23,7 @@ RUN pip install ansible-core \
                 ansible-lint
 
 RUN ansible-galaxy collection install community.docker
+RUN ansible-galaxy collection install community.general
 
 ADD cmd.sh /cmd.sh
```

After that the local test against my role succeeds.

**Comment by robertdebock** [comment]
With the merge of a PR, this issue should be resolved.
