### ISSUE TITLE
You need to install "jmespath" prior to running json_query filter

### ISSUE THREAD

**Issue by Normo** [robertdebock/docker-github-action-molecule#3]
The package `jmespath` is required to use the json_query filter: https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#json-query-filter

**Comment by robertdebock** [comment]
Hi, sorry to have missed this issue.

I don't fully understand why json_query is required. Can you explain a little more?

**Comment by Normo** [comment]
Hi @robertdebock,

I'm using a role which uses json_query - see here: https://github.com/elastic/ansible-elasticsearch#dependency

**Comment by robertdebock** [comment]
That's a good usecase, I'll work on it and release a new version later. Thanks!

**Comment by Normo** [comment]
Please consider my pull request #4.

**Comment by robertdebock** [comment]
New action ([2.1.0](https://github.com/marketplace/actions/test-ansible-roles-with-molecule)) has just been released which should fix your issue.

Thanks again for the feedback!
