### ISSUE TITLE
Some images dont contain Python

### ISSUE THREAD

**Issue by dgibbs64** [robertdebock/docker-github-action-molecule#30]
I am using your awesome action to test my roles. I created a very simple role that has a local action. However, a number of the images fail because python is not installed.

```
fatal: [generate-ssh-keys-alpine-latestpy310-ansible-4]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "/bin/sh: /usr/bin/python: not found\n", "module_stdout": "", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}
```

This failed on OpenSUSE, Alpine and Debian images. Please could you add the python package to these images.

Thank you

**Comment by robertdebock** [comment]
Hi,

The images indeed do not have Python installed, but the [bootstrap role](https://galaxy.ansible.com/robertdebock/bootstrap) takes care of python and sudo.

My thought about this: Systems may have python or not, so I'd like to test on "generic" images. Hope you agree here. ;-)

**Comment by dgibbs64** [comment]
Thanks for your response it made me realise I have confused myself. The role I am building is a "local only" role and I wanted to do tests against different ansible controller distros. However the images are for the the remote host. I also forgot to make a task a local_action. Having a nightmare 😆 
 
https://github.com/dgibbs64/ansible-role-generate-ssh-keys
