### ISSUE TITLE
Run multiple molecule scenarios

### ISSUE THREAD

**Issue by till** [robertdebock/docker-github-action-molecule#5]
Hi,

it seems the action doesn't run all scenarios:
https://github.com/hostwithquantum/ansible-loki/pull/4/checks?check_run_id=860713499

It seems to run `default`, but not the `update` scenario.

Is there a way to do a `molecule test --all` without something like tox? I am not keen on adding another thing. I couldn't figure out how to add parameters to molecule otherwise. Any pointers? I am happy to add the action multiple times too, so I can run the tests in parallel easily.

Till

**Comment by till** [comment]
This seems to confirm it:
https://github.com/robertdebock/docker-github-action-molecule/blob/master/Dockerfile#L18

**Comment by robertdebock** [comment]
Hi @till, you are right, it only runs `default` now.

Let me see how I can change that.

I think user want the option to be able to specify a name of a scenario, like:

```
molecule test --scenario-name foo
```

And have the option to test all:

```
molecule test --all
```

so the inputs could be changed to something like this:
```markdown
## scenarios: Specify the name of a scenario. Defaults to `default`.
```

Do you think `molecule test --all` be the default action?

**Comment by till** [comment]
Yeah,good question. I guess `--all` is a good default?

I like your scenario option/input!

Thanks for taking a look!

**Comment by till** [comment]
@robertdebock I thought about this a bit.

I think with an input for `scenario` (singular), the `--all` is not needed.

I think I'd rather use the action multiple times, then having to untangle it. So I can run my scenarios in parallel, for example, or enable only certain scenarios, etc..

If you'd like, I can PR the change?

**Comment by robertdebock** [comment]
Hi @till.

It's ready to be used, can you test version 2.6.0 and let me know if the suits your needs?

Regards, Robert de Bock.

**Comment by robertdebock** [comment]
Closing, but let me know if you need something else. Thanks @till!

**Comment by till** [comment]
Doesn't seem to work, or am I missing something?
https://github.com/hostwithquantum/ansible-loki/pull/7/commits/d3dcc2596963c9c6a8e1d120be6d45fd37b3769d#diff-ee0ca3d1e1ab385d3ada60bac977afbcR14-R19

**Comment by till** [comment]
Looks like it's missing here:
https://github.com/robertdebock/molecule-action/blob/ababe15c11e2e33c07bf4e3c95b2e52c1398cc1e/action.yml#L33-L38

**Comment by till** [comment]
@robertdebock I would re-open, but I can't.

**Comment by robertdebock** [comment]
You are correct, missed that, sorry!

**Comment by robertdebock** [comment]
This should be solved with version 2.6.1. Sorry for the inconvenience, thanks for helping me out!

**Comment by till** [comment]
I'll test when I get back! Thank you!

**Comment by till** [comment]
Works! :) Thanks again!
