### ISSUE TITLE
No mail on success

### ISSUE THREAD

**Issue by bbaassssiiee** [robertdebock/docker-github-action-molecule#8]
I get an email when the build fails, but none when it succeeds.

**Comment by robertdebock** [comment]
The emails you receive (on failures only) are a built-in function for GitHub.

Please change the settings under your [personal settings](https://github.com/settings/notifications) -> GitHub Actions.

Hope that addresses the issue, otherwise, feel free to re-open. Thanks Bas!

**Comment by bbaassssiiee** [comment]
I unchecked 'Send notifications for failed workflows only', thanks!
